### ISSUE TITLE
Thanks for it / how can I use it?

### ISSUE THREAD

**Issue by piotr-yuxuan** [farbetter/roe#1]
You project seems quite promising but you offer no help to get started apart from src and test. That's true Thou Shalt Use the Source, Luke, but any basic show case would probably do it.

Anyway, thanks for that project :-)

**Comment by piotr-yuxuan** [comment]
Plus I can see you're alone on this project. What about writing a roadmap or emphasizing low-hanging fruits for newcomers?

**Comment by chadharrington** [comment]
This project is deprecated. I will update the Readme. I created a much faster, easier to use, and more standard-compliant Avro library for Clojure: https://github.com/deercreeklabs/lancaster
Unfortunately, that project is not documented, either. :-( I hope to document it sometime, but have not had the time. If you are adventurous, look at the lancaster.cljc top-level API and the examples in lancaster_test.cljc.
